# backend/Dockerfile
FROM node:22-alpine

WORKDIR /app

# התקנת תלויות
COPY package*.json ./
RUN npm ci --omit=dev || npm install --omit=dev

# העתקת קוד
COPY . .

# יציאה (Express מאזין על 5000)
EXPOSE 5000

# מומלץ להגדיר NODE_ENV=production בזמן הרצה בענן
ENV NODE_ENV=production

CMD ["node", "server.js"]
