# backend/nixpacks.toml
[phases.setup]
# גרסת Node (כמו שהלוג מראה)
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
# התקנה אחת נקיה
cmds = ["npm ci"]

[phases.build]
# אין בניה נפרדת לשרת אקספרס
cmds = []

[start]
# מריץ את השרת שלנו
cmd = "node server.js"
