# backend/nixpacks.toml
[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci --no-audit --no-fund"]

[phases.build]
cmds = [] # אין שלב build לשרת express

[start]
cmd = "node server.js"
